package com.objectfrontier.training.habs.api;

public enum AppErrorCode {

	UNKNOWN_ERROR,
	
	HOSPITAL_INVALID_NAME, 
	HOSPITAL_NOT_FOUND, 
	
	DOCTOR_NAME_NULL,
	DOCTOR_SPECIALIZATON_NULL,
	DOCTOR_DEPARTMENT_NULL,
	DOCTOR_NOT_FOUND,
	DOCTOR_SPECIALIZATON_NOTFOUND, 
	
	PATIENT_NAME_NULL, 
	PATIENT_AGE_ZERO_OR_NEGATIVE,
	PATIENT_DISEASE_NULL, 
	PATIENT_GENDER_NULL, 
	PATIENT_NOT_FOUND,
	PATIENT_DISEASE_NOTFOUND;
	
	@Override
	public String toString() {
		return name();
	}
	
}
