/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kandavela' at '4/28/16 4:03 PM' with Gradle 2.6
 *
 * @author kandavela, @date 4/28/16 4:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
